name: 'Move Issues To Project Column'
description: 'Move issues to a column based on the issue marker. Move linked PR(child PRs too) issues to column on close and merge event.'
author: 'fojia'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github_token:
    description: GitHub token.
    required: false
  owner:
    description: Project Owner.
    required: true
  repo:
    description: Repository with PR.
    required: true

  fieldID:
    description: ID of field to change
    required: true
  optionID:
    description: Option to change field to
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
