name: 'Move Issues To Project Column'
description: 'Move issues to a specific project column based on the issue marker. Move linked PR(including child PRs) issues to specific project column on close and merge event.'
author: 'fojia'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github_token:
    description: GitHub token.
    required: false
  project:
    description: Project Name.
    required: true
  column:
    description: Project Column Name.
    required: true
  marker:
    description: Substring to mark issue.  
    required: false
    default: ''
  type:
    description: Project Type (org, repo, user).
    required: true
    default: 'repo'
  owner:
    description: Project Owner.
    required: true
  repo:
    description: Project Repository.
    required: false
  branch:
    description: The PR's destination branch.
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
